### ISSUE TITLE
When upgrading, clearwater-snmp-handler-alarm package is not completely removed

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/clearwater-snmp-handlers#104]
When upgrading from a release with ```clearwater-snmp-handler-alarm``` to one with ```clearwater-snmp-alarm-agent``` the ```clearwater-snmp-handler-alarm``` package is not completely removed. This doesn't seem to cause any problems, but it's confusing when looking at what's installed. I temporarily fixed this in my load with the following change to ```clearwater-snmp-alarm-agent's``` Debian control file:

```
@@ -16,6 +16,8 @@ Description: The SNMP handler library for statistics about the Call Diversion AS
 
 Package: clearwater-snmp-alarm-agent
 Architecture: any
+Breaks: clearwater-snmp-handler-alarm
+Replaces: clearwater-snmp-handler-alarm
 Depends: clearwater-snmpd, libboost-filesystem1.54.0
 Description: The SNMP subagent for Clearwater alarm reporting
```

**Comment by rkd-msw** [comment]
@bossmc - fixed by https://github.com/Metaswitch/clearwater-snmp-handlers/pull/106?

**Comment by dtheobald** [comment]
Yes
