### ISSUE TITLE
ActiveAlarmTable handler should have a mechanism for ensuring sychronization with alarmers

### ISSUE THREAD

**Issue by steelyvoid** [Metaswitch/clearwater-snmp-handlers#108]
The soon-to-be-introduced ActiveAlarmTable handler doesn't maintain persistent alarm state in a way that won't be lost if and when the handler goes down for whatever reason (e.g. during planned maintenance).

This means that alarms that are raised when a particular component changes state (e.g. an Astaire "starting to sync" alarm) will be lost should the ActiveAlarmTable handler restart or be down at the point that the alarm is raised.

We should have a mechanism (e.g. periodically reraising alarms in the component itself, even if the component knows it has successfully raised the alarm) that ensures that the ActiveAlarmTable handler (eventually) presents an accurate view of the alarm state of the node to the NMS

**Comment by chris-elford-metaswitch** [comment]
I'm expecting that we can solve this as part of our current push on alarm reliability. Details to follow.

**Comment by chris-elford-metaswitch** [comment]
Rob,

Does your new plan for improved alarm reliability address Steve's concern?

**Comment by rkd-msw** [comment]
The work done last sprint actually addresses this concern:

* C++ components retransmit active alarms to the alarm handler every 30s - see https://github.com/Metaswitch/cpp-common/blob/149f2112fd0e1953fec0646274ff150b2161901a/src/alarm.cpp#L208
* Python components retransmit active alarms to the alarm handler every 30s - https://github.com/Metaswitch/python-common/blob/dev/metaswitch/common/alarms.py#L161
* If alarms are raised/cleared from scripts, not components, we've ensured that that happens regularly (e.g. monit re-clears process failure alarms every time a poll script passes, not just once when the process has been up for 30s)

This means that if the alarm agent restarts, or is down when the alarm is raised, the active alarm table will be accurate 30 seconds after it comes back up.

**Comment by steelyvoid** [comment]
Thanks Guys - I'm happy to close this issue
