### ISSUE TITLE
Tests in clearwarer-snmp-handlers and clearwater-fvtest create a SNMP agent on the same address.

### ISSUE THREAD

**Issue by AME2** [Metaswitch/clearwater-snmp-handlers#116]
Both clearwater-snmp-handlers/fvtest.conf and clearwater-fv-test/src/fvtest.conf register an SNMP agent on address 16161. This causes the clearwater-snmp-handlers build to fail in Jenkins as clearwarer-fv-test is built first.

To find this we should change the address of the SNMP agent within clearwater-snmp-handlers/fvtest.conf and then modify the snmp commands (snmp_get_raw and snmp_walk) to use the correct SNMP agent.

**Comment by rkd-msw** [comment]
Is this now fixed?

**Comment by AME2** [comment]
Yes it is.
This was fixed by including a constructor in the SNMPTest class within cpp-common that sets the address of the alarm agent that the snmp_get and snmp_walk member functions use.
Then in Clearwater_snmp_handlers in the CustomDefs class (which is a subclass of SNMPTest) its default constructor called the SNMPTest constructor to set the alarm agent to a different value (16162 as opposed to 16161 used in clearwater_fv_test).
