### ISSUE TITLE
Over aggressive filtering of alarms in the Alarm Trap Sender

### ISSUE THREAD

**Issue by AME2** [Metaswitch/clearwater-snmp-handlers#128]
The alarm_filtered function defined within the Alarm Trap Sender will currently filter out an alarm if it has been raised with the same state within 5 seconds. This is to stop a flickering alarm causing a high volume of SNMP informs to be sent to an NMS.
This behaviour though is too aggressive and could cause the NMS to be out of sync- If an alarm is CLEARED, raised (in a non-CLEARED state) and then CLEARED again, the NMS would believe the alarm is raised as the last CLEARED would have been filtered out.

**Comment by eleanor-merry** [comment]
Fixed in https://github.com/Metaswitch/clearwater-snmp-handlers/pull/147
