### ISSUE TITLE
Enterprise MIB alarms do not display the hostname of the node raising the alarm

### ISSUE THREAD

**Issue by AME2** [Metaswitch/clearwater-snmp-handlers#170]
In the Clearwater test team we use a shared alarm sink to capture all the alarms raised across all of the test deployments we have created.

We've found it difficult to search for alarms that have been risen from a certain deployment, you have to think about the IP address of every node in your deployment and then use this in a grep command.

This is an issue which could also affect customers, if they are using an NMS which doesn't allow you to preconfigure a node's hostname to its IP address then there would be no immediately way to see which node on which deployment has raised the alarm.

It would be better if the hostname were included in the alarm trap, then you could search for the domain name of a deployment or you could search for "Sprout" say to find all alarms raised from Sprout nodes.

To reproduce this create a deployment which uses Enterprise MIB alarms and raise an alarm.

**Comment by rkd-msw** [comment]
Marking as critical as this relates to new function. The goal of using enterprise MIBs for alarms is to make them as easy as possible to integrate with, so I think we want to avoid having the requirement that anything which receives alarms from Clearwater must be capable of mapping management IP addresses to hostnames.

**Comment by rkd-msw** [comment]
Fixed:

```
Jan 29 23:39:28 utility-server snmptrapd[31473]: 2017-01-29 23:39:28 <UNKNOWN> [UDP: [10.225.166.90]:58974->[10.225.166.11]:162]:#012SNMPv2-SMI::mib-2.1.3.0 = Timeticks: (29420567) 3 days, 9:43:25.67#011SNMPv2-SMI::snmpModules.1.1.4.1.0 = OID: CLEARWATER-ENTERPRISE-MIB::alarmTrap#011CLEARWATER-ENTERPRISE-MIB::clearwaterInfoVersion = STRING: 201608081100#011CLEARWATER-ENTERPRISE-MIB::alarmTrapDisplayName = STRING: HOMESTEAD_PROCESS_FAIL#011CLEARWATER-ENTERPRISE-MIB::alarmTrapAlarmOID = OID: SNMPv2-SMI::mib-2.118.1.1.2.1.3.0.1500.2#011CLEARWATER-ENTERPRISE-MIB::alarmTrapResourceID = OID: SNMPv2-SMI::zeroDotZero#011CLEARWATER-ENTERPRISE-MIB::alarmTrapSeverity = STRING: CLEARED#011CLEARWATER-ENTERPRISE-MIB::alarmTrapDescription = STRING: Homestead: Process failure cleared.#011CLEARWATER-ENTERPRISE-MIB::alarmTrapDetails = STRING: The Homestead process has been restored to normal operation.#011CLEARWATER-ENTERPRISE-MIB::alarmTrapCause = STRING: The Homestead process has been restored to normal operation. The previously issued alarm has been cleared.#011CLEARWATER-ENTERPRISE-MIB::alarmTrapEffect = STRING: Full capacity and availability of the connected HSSs has been restored for the I-CSCF and the S-CSCF.#011CLEARWATER-ENTERPRISE-MIB::alarmTrapAction = STRING: No action.#011CLEARWATER-ENTERPRISE-MIB::alarmTrapHostname = STRING: rkd-homestead-1.rkd.clearwater.test
```

(the crucial bit is `CLEARWATER-ENTERPRISE-MIB::alarmTrapHostname = STRING: rkd-homestead-1.rkd.clearwater.test`)
