### ISSUE TITLE
Alarms and statistics don't work after node reboot

### ISSUE THREAD

**Issue by dtheobald** [Metaswitch/clearwater-snmp-handlers#39]
On reboot Ubuntu removes the /var/run/clearwater directory that is used as a repository for the Unix domain sockets used by alarms and statistics. The start up scripts don't re-create the directory, so alarms and statistics no longer work after a reboot.

I tried to fix this by adding a script that re-created the directory to '/usr/share/clearwater/infrastructure/scripts/'. Unfortunately, clearwater-infrastructure's RC scripts don't run until after snmpd's, so alarms still didn't work. Not being fully aware of the reason behind the RC ordering, I was not inclined to reorder anything. As such, I worked around the problem by editing (during install) snmpd's init.d script to re-create the directory. I'm not planning on submitting a pull request with my change since it's a bit wonky and someone in the know (on the PC team) will have a better solution.

**Comment by rkd-msw** [comment]
I think this is https://github.com/Metaswitch/clearwater-infrastructure/issues/127, fixed by https://github.com/Metaswitch/clearwater-infrastructure/pull/128. (Looks like that's essentially your original change, plus the X-Start-Before changes you were cautious about making.)

**Comment by dtheobald** [comment]
Closing as a duplicate.
