### ISSUE TITLE
Process 'alarm_agent_process' does not exist

### ISSUE THREAD

**Issue by graemerobertson** [Metaswitch/clearwater-snmp-handlers#85]
On the Staging Homer node Monit is reporting that

`Process 'alarm_agent_process'       Does not exist`

ps shows that cw_alarm_agent is running (if that's related; I assume it is)

`/usr/share/clearwater/bin/cw_alarm_agent -i 0.0.0.0 -c clearwater`

**Comment by eleanor-merry** [comment]
I think this is a chef bug. Homer shouldn't have clearwater-snmp-alarm-agent installed in the first place as it doesn't have alarms.

**Comment by eleanor-merry** [comment]
Closed in https://github.com/Metaswitch/chef/pull/227
