### ISSUE TITLE
net-snmp proxying compares against the wrong range

### ISSUE THREAD

**Issue by TygerBurning** [Metaswitch/clearwater-snmp-handlers#89]
When proxying an OID, net-snmp may incorrectly say it is out of range as it compares the base OID (i.e. the proxy *to* location) rather than the name OID (i.e. the proxy *from* location) to the user requested OID.

Therefore it returns the first thing that the base is pointing to, because it thinks you are outside the range (in the process discarding any information you may have tagged on)

The relevant line is [here:](http://sourceforge.net/p/net-snmp/code/ci/master/tree/agent/mibgroup/ucd-snmp/proxy.c#l415)

The fix is to replace this with:
```
(snmp_oid_compare(ourname, ourlength,
      sp->name, sp->name_len) < 0)) {
```

**Comment by eleanor-merry** [comment]
@bossmc - have you fixed this now?

**Comment by bossmc** [comment]
Yes, the patched version of net-snmp is built from https://github.com/Metaswitch/clearwater-net-snmp and installed as a dependency by appropriate packages.
